language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer install

cache:
  directories:
    - $HOME/.php-cs-fixer

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml;
  - php ./vendor/bin/php-cs-fixer fix --config=.php_cs.php --verbose --diff --dry-run --allow-risky=yes;
